### ISSUE TITLE
Fatal Crash - SE Discord

### ISSUE THREAD

**Issue by iceystreeeet** [TorchAPI/TorchDiscord#1]
I am having to reboot my whole rack box every three days about. The SE_Discord goes offline in the discord and i try the reload command crashes my server. I then reopen Torch and get a hell of bunch of errors as seen above. IF the plugin dev is active why is he not answering this topic? The only way to fix it is to reboot the whole server box. I do not have a VPS i have a whole Rack mounted box.

[Torch-2021-01-31.txt](https://github.com/TorchAPI/TorchDiscord/files/5900711/Torch-2021-01-31.txt)

Please see the Help section on the Torch discord.

We know its not the network

It's not the network. We have had a Wireshark on the connection for the past week. And a flow Analyzer no drops in internet connection I have a 5 GB up and down on my server box. I pay a 100 to host my personal box in a DC. Colocation. We have done that the only way to fix this is to restart the actual rack box.

**Comment by Jimmacle** [comment]
You aren't using the plugin this repository is for and this log indicates an unrelated issue with your server being unable to reach the Torch website to check for updates.
